targets:
  $default:
    builders:
      json_serializable:
        options:
          any_map: true
          explicit_to_json: true
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - "type=lint"